title: Nature's Lover
author: Harsh
email: bhardwajharsh08@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Greetings Comrade!!
  I am a Nature Lover. On a mission to see the Earth and other Life Forms.
  Wish Me Luck!
  So Let's Start Dreaming.

# social links
twitter_username: H4harshbhardwaj
github_username:  Eddy08

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
